# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI


on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing Packages
        run: npm ci
      - name: Checking Formatting
        run: npm run lint && npm run prettier --write && npm run prettier-check
      - name: Code Coverage
        run: npm run coverage
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  slither:
    runs-on: ubuntu-latest
    name: Solidity Security - Slither
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'
      - uses: actions/setup-python@v2
        with:
         python-version: '3.8'
      - name: Prepare environment
        run: |
         npm install -g ganache-cli@6.12.1
         pip3 install solc-select
         solc-select install 0.5.17
         solc-select use 0.5.17
         pip3 install slither-analyzer
        #  pip install -r requirements-dev.txt
      # - name: Prepare contracts
      #   shell: bash
      #   run: |
      #     # npm run clone-packages
      #     npm run sec:flatten
      - name: Slither Static Analysis
        uses: luisfontes19/slither-static-analysis-action@v0.3.2
        with:
          slither-version: '0.6.13'
          run-npm-install: true
          high-threshold: 0
          medium-threshold: 20
          low-threshold: 30
          optimization-threshold: 5
          informative-threshold: 50
          projectPath: "./contracts"
